version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dev/WEB
    volumes:
    - .:/app
    ports:
    - "80:80"
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuserwithpassword --username admin --password admin --email admin@example.org --preserve &&
      python manage.py runserver 0.0.0.0:80"
  postgres:
    build:
      context: .
      dockerfile: docker/Dev/DB
    restart: unless-stopped
    expose:
      - "5432"
    environment:   # will be used by the init script
      LC_ALL: C.UTF-8
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassowrd
      POSTGRES_DB: mydb
    volumes:
    - .:/posgre