# Generated by Django 3.0 on 2020-01-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Choice', 'Choice'), ('Text', 'Text Field'), ('Int', 'Integer Field')], default='Choice', max_length=200),
        ),
    ]
